---
version: 2
plan:
  project-key: PROJ
  key: AS
  name: ASA-MAIN

stages:
  - Stage 1:
      jobs:
        - Job 1

Job 1:
  tasks:
    - script:
        - echo 'Hello from YAML Specs'
