---
version: 2
plan:
  project-key: ASA
  key: AS
  name: ASA-MAIN

stages:
  - Stage 1:
      jobs:
        - Job 1

Job 1:
  tasks:
    - script:
        - echo 'I am sahan kudaketiyapege'
